name: run
 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY: ${{ secrets.OPENDART_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        cache: 'pip'
        python-version: '3.9'
        cache-dependency-path: './requirements.txt'
    
    - name: 정보 조회
      run: |
        echo $GITHUB_WORKSPACE
        ls -al
        python -V

    - name: 환경 설정
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 패키지 확인
      run: pip list

    - name: run script
      run: python ./main.py $KEY